# vhost SSL pour tmplanning.jelobox.fr

<VirtualHost *:80>

        # redirection de http://tmplanning.jelobox.fr -> https://tmplanning.jelobox.fr

        ServerName tmplanning.jelobox.fr

        # si pas de https alors on réécrit l'URL avec https
        <IfModule mod_rewrite.c>
                RewriteEngine on
                RewriteCond %{HTTPS} off
                RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
        </IfModule>


</VirtualHost>


<IfModule mod_ssl.c>
  <VirtualHost *:443>

        ServerAdmin jlzola@gmail.com
        ServerName tmplanning.jelobox.fr



        #
        # Configuration SSL

        SSLEngine On

        # Exclue les protocoles de configuration obsolettes
        SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1

        #clé de cryptage long uniquement
        #SSLCipherSuite ALL:!DH:!EXPORT:!RC4:+HIGH:+MEDIUM:!LOW:!aNULL:!eNULL
        SSLCipherSuite   ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-$

        SSLHonorCipherOrder on
        #SSLCompression      off
        #SSLSessionTickets   off


        #log
        ErrorLog ${APACHE_LOG_DIR}/error_tmplanning.log

        # Possible values include: debug, info, notice, warn, error, crit, alert, emerg.
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/access_tmplanning.log combined




        #
        # Let'Encrypt  jelobox.fr
        SSLCertificateFile  /etc/letsencrypt/live/jelobox.fr/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/jelobox.fr/privkey.pem


        # rewriting
#       <IfModule mod_rewrite.c>
#               RewriteEngine On
#               RewriteRule ^/$ /web/ [L,R=301]
#       </IfModule>


        #
        # redirection
        ProxyPreserveHost On
        ProxyRequests off
        ProxyPass / http://localhost:3000/
        ProxyPassReverse / http://localhost:3000/


        # Autoriser l'accès au contenu à travers le proxy.
        # Ne l'enlevez pas si vous voulez que le site fonctionne !
        <Location />
                Order deny,allow
                Allow from all
        </Location>


  </VirtualHost>
